clone:
  depth: 20
  recursive: true
  submodule_update_remote: true

build:
  image: tuxity/drone-gulp-bower
  pull: true
  commands:
    - npm install -q
    - bower install --allow-root --production
    - gulp

deploy:
  sftp:
    host: sheaker.com
    username: ubuntu
    destination_path: /tmp/sheaker-front
    files:
      - dist
      - .deploy
    when:
      branch: master
  ssh:
    host: sheaker.com
    user: ubuntu
    commands:
      - /tmp/sheaker-front/.deploy/remote.sh
    when:
      branch: master

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: notifications
    username: Drone
    template: >
      Build <https://drone.sheaker.com/{{ repo.full_name }}/{{ build.number }}|{{ repo.name }}#{{ truncate build.commit 7 }}> ({{ build.branch }}) by {{ build.author }} finished with a *{{ build.status }}* status in {{ duration build.started_at build.finished_at }}
