image: node0.10
script:
    - npm install -g bower gulp
    - npm install
    - bower install
    - gulp
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    on_started: false
    on_success: true
    on_failure: true
