image: neo9polska/nodejs-bower-gulp

script:
  - npm install
  - bower install --allow-root
  - gulp

deploy:
  ssh:
    target: ubuntu@ec2-52-20-239-124.compute-1.amazonaws.com:~/sheaker-front.tar
    artifacts:
      - dist
      - .deploy
    cmd: mkdir sheaker-front; tar -xf sheaker-front.tar -C sheaker-front; cd sheaker-front; .deploy/remote.sh
    when:
      branch: master

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    on_started: false
    on_success: true
    on_failure: true
